package com.shepeliev.webrtckmp

expect class RtcConfiguration(
    iceServers: List<IceServer> = emptyList(),
    iceTransportsType: IceTransportsType = IceTransportsType.All,
    bundlePolicy: BundlePolicy = BundlePolicy.Balanced,
    certificate: RtcCertificatePem? = null,
    rtcpMuxPolicy: RtcpMuxPolicy = RtcpMuxPolicy.Require,
    tcpCandidatePolicy: TcpCandidatePolicy = TcpCandidatePolicy.Enabled,
    candidateNetworkPolicy: CandidateNetworkPolicy = CandidateNetworkPolicy.All,
    audioJitterBufferMaxPackets: Int = 50,
    audioJitterBufferFastAccelerate: Boolean = false,
    iceConnectionReceivingTimeout: Int = -1,
    iceBackupCandidatePairPingInterval: Int = -1,
    keyType: KeyType = KeyType.ECDSA,
    continualGatheringPolicy: ContinualGatheringPolicy = ContinualGatheringPolicy.GatherOnce,
    iceCandidatePoolSize: Int = 0,
    turnPortPrunePolicy: PortPrunePolicy = PortPrunePolicy.NoPrune,
    presumeWritableWhenFullyRelayed: Boolean = false,
    surfaceIceCandidatesOnIceTransportTypeChanged: Boolean = false,
    iceCheckIntervalStrongConnectivityMs: Int? = null,
    iceCheckIntervalWeakConnectivityMs: Int? = null,
    iceCheckMinInterval: Int? = null,
    iceUnwritableTimeMs: Int? = null,
    iceUnwritableMinChecks: Int? = null,
    stunCandidateKeepaliveIntervalMs: Int? = null,
    disableIpv6OnWifi: Boolean = false,
    maxIPv6Networks: Int = 5,
    disableIpv6: Boolean = false,
    enableDscp: Boolean = false,
    enableCpuOveruseDetection: Boolean = true,
    enableRtpDataChannel: Boolean = false,
    suspendBelowMinBitrate: Boolean = false,
    screencastMinBitrate: Int? = null,
    combinedAudioVideoBwe: Boolean? = null,
    enableDtlsSrtp: Boolean? = null,
    networkPreference: AdapterType = AdapterType.Unknown,
    sdpSemantics: SdpSemantics = SdpSemantics.PlanB,
    activeResetSrtpParams: Boolean = false,
    allowCodecSwitching: Boolean? = null,
    cryptoOptions: CryptoOptions? = null,
    turnLoggingId: String? = null,
)
