name: Build Linux

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    name: Build and test Android/JS/WasmJS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          cache: gradle

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: Cache konan directory
        uses: actions/cache@v3
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('*.gradle.kts', 'buildSrc/*') }}
          restore-keys: |
            ${{ runner.os }}-konan-  

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Run Android instrumented tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: google_apis
          arch: x86_64
          profile: Nexus 6
          script: ./gradlew webrtc-kmp:connectedAndroidTest

      - name: Upload Android test artifact
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: "Android Instrumented Tests Report HTML"
          path: "webrtc-kmp/build/reports/androidTests/connected"

      - name: Run JS tests
        run: ./gradlew cleanTest kotlinUpgradeYarnLock webrtc-kmp:jsTest

      - name: Upload JS test artifact
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: "JS Tests Report HTML"
          path: "webrtc-kmp/build/reports/tests/js*Test"

      - name: Run WasmJS tests
        run: ./gradlew cleanTest kotlinUpgradeYarnLock webrtc-kmp:wasmJsTest

      - name: Upload WasmJS test artifact
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: "JS Tests Report HTML"
          path: "webrtc-kmp/build/reports/tests/wasmJs*Test"

      - name: Build sample app
        run: ./gradlew sample:composeApp:assemble
